### ISSUE TITLE
More button on profile is not clickable

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#130]
What does the more button do? Currently there is no designs in place for it. 

## UPDATE
We should delete this button and remove some of the space (on internal profile view)

<img width="371" alt="screen shot 2017-08-30 at 9 59 39 pm" src="https://user-images.githubusercontent.com/14966713/29902837-9ba9962a-8dce-11e7-802e-309d101ea296.png">

**Comment by doctor3w** [comment]
It's clickable nothing happens yet though. We need to decide on what that does.

**Comment by doctor3w** [comment]
It's been removed now.
