### ISSUE TITLE
Followers / Following table views need to be implemented 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#131]
Currently, these buttons do not do anything .. We need to push a table view with followers and following lists (we need designs) 

<img width="378" alt="screen shot 2017-08-30 at 10 00 50 pm" src="https://user-images.githubusercontent.com/14966713/29902884-ce7bdcca-8dce-11e7-9dfd-4ca56732bafb.png">

**Comment by doctor3w** [comment]
Done. The button numbers are funky but I think that's a backend thing.
