### ISSUE TITLE
Weird space at end of profile table view

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#146]
<img width="376" alt="screen shot 2017-09-12 at 5 13 54 pm" src="https://user-images.githubusercontent.com/14966713/30355006-6f077102-97fe-11e7-8576-4ae5ce126718.png">

**Comment by doctor3w** [comment]
Update on this. I don't know the exact height, if you do, update the static height there. I have a good guess in, mitigating this unless you have a ton of recommendations.

**Comment by doctor3w** [comment]
Update: Will be fixed in Issue #200

**Comment by natashaarmbrust** [comment]
Same issue that I just assigned you two so I am closing this
