### ISSUE TITLE
Bottom of SearchTableView goes off page 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#180]
<img width="354" alt="screen shot 2017-10-23 at 4 45 25 pm" src="https://user-images.githubusercontent.com/14966713/31912366-a0ad1bac-b811-11e7-929e-67fba051cdb3.png">

**Comment by doctor3w** [comment]
We need some way to set the search tableviews as the mainScrollView so that the tab bar inset automatically handles this.

**Comment by dantheli** [comment]
Fixed with SnapKit. See branch `daniel/fix-constraints`

**Comment by doctor3w** [comment]
I fixed this actually with a new function in search view controller, how did you do it with snapkit while maintaining the translucent tab bar? @dantheli
