### ISSUE TITLE
make buttons bigger EVERYWHERE

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#195]

**Comment by natashaarmbrust** [comment]
Additional issues that should be fixed in PR that addresses this:
1. make mini player Play / Pause icon bigger
2. Dismiss player chevron is too small
3. Sliding should collapse the player not just tap at the top (gesture recognizer) [MAKE SEPARATE ISSUE]

**Comment by doctor3w** [comment]
Make number 3 in that list a separate issue that will be difficult.

**Comment by doctor3w** [comment]
Number 3 is now in issue #124
