### ISSUE TITLE
Redo profile to be a custom scroll view

### ISSUE THREAD

**Issue by doctor3w** [cuappdev/podcast-ios#200]
Currently it's a table view with a cels that contain collection views and table views. This is bad. It's also the culprit of the weird space from dynamic cells.

**Comment by doctor3w** [comment]
This will also make profile header SnapKit compliant.

**Comment by doctor3w** [comment]
This will also add the null states for profile when a user has no subscriptions and no recommendations.

**Comment by natashaarmbrust** [comment]
This should also fix the refresh the profile views when state changes ... i.e. if I unfollow a user this should reflect in my following count when I return to profile

**Comment by natashaarmbrust** [comment]
![img_6b17673f579b-1](https://user-images.githubusercontent.com/14966713/36738603-ef650ebe-1bab-11e8-9b7c-5a670635fc03.jpeg)

**Comment by natashaarmbrust** [comment]
YAY newb now gets this issue .. @mindylou 's `ScrollView` / `Discover` branch should help you here so speak with her before implementing

**Comment by natashaarmbrust** [comment]
Also the reason for this is that we dynamically resize the episode table view cells but have a set height for the tableview which is wrong

**Comment by natashaarmbrust** [comment]
I'm assigning this to @mindylou

**Comment by natashaarmbrust** [comment]
it would be great to have this done for tomorrow but obviously not necessary! depends how much time you have :)
