### ISSUE TITLE
Integrate Realm 

### ISSUE THREAD

**Issue by Jma353** [cuappdev/podcast-ios#22]
I will consult Dan Li for this

**Comment by dennisfedorko** [comment]
We're going to need to integrate realm for tempo as well, so we should probably discuss team standards for how we should store data locally, so it's consistent across our products.

**Comment by Jma353** [comment]
@dantheli has an extremely solid understanding of it.  I think he should drive the standard-creation process, and I'll go off what he says.

**Comment by dantheli** [comment]
Thanks Joe. I'd be happy to contribute to a Realm standard for the team

**Comment by celinebrass** [comment]
omg.  you can add reactions to issue comments!! 

#githubstrynabeslack i c u.
