### ISSUE TITLE
Fix padding / text on Player to include the entire detail string 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#246]
There should be no dots, the detail string should auto adjust to be necessary number of lines 

![img_1060](https://user-images.githubusercontent.com/14966713/36501360-ea20a8fa-1714-11e8-809b-a09a2ec2df5b.PNG)

**Comment by jackthmp** [comment]
Should I fix this in the expanded artwork view of the player too?

**Comment by natashaarmbrust** [comment]
Yes!
