### ISSUE TITLE
unsupported URL error

### ISSUE THREAD

**Issue by inardo** [cuappdev/podcast-ios#259]
I'm getting this error when trying to sign in. Any ideas?

Task <79D85877-20B0-494B-A188-EE88B405D96C>.<3> finished with error - code: -1002
unsupported URL
/users/google_sign_in/

**Comment by natashaarmbrust** [comment]
Yup. We refactored our backend api url to be in the `Keys.plist`. You will see `api-url` has an empty string in that property list. We have made it so only our team's developers can access the backend url.
