### ISSUE TITLE
I can't sign in, it's saying "that's technology for ya"

### ISSUE THREAD

**Issue by scholargifer** [cuappdev/podcast-ios#268]
I can't sign in, when I try to sign in with google or facebook, I get an error that says  "Whoops an error occured! that's technology for ya". How can I fix this?

**Comment by mindylou** [comment]
Right now our backend url is only available to our team's developers in `Keys.plist`, so the app will not connect without it. Please see #259 for more information. If you would like to use the app, please clone our team's [backend repository. ](https://github.com/cuappdev/podcast-backend)

**Comment by scholargifer** [comment]
Do I have to copy and paste the podcast-backend into the podcast-ios
folder? I'm new to this. Thanks for your help.

**Comment by natashaarmbrust** [comment]
You would need to clone the backend repo and run it locally and connect to the url of that repo

**Comment by natashaarmbrust** [comment]
I can add you to our testflight if you are just trying to use the app

**Comment by scholargifer** [comment]
Yes, you can do that and as my skills improve, I'd like to contribute if
that's okay.

**Comment by natashaarmbrust** [comment]
contributions from the outside community are welcome .. feel free to put up a PR

**Comment by natashaarmbrust** [comment]
I need your first name, last name, email to add you to testflight
