### ISSUE TITLE
Subscribe button sometimes off in feed

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#283]
![97ad0196-5143-4336-ad7c-16c7be1f7c41](https://user-images.githubusercontent.com/14966713/37017331-5332431c-20de-11e8-8f02-d727fa8222a6.png)
![0b6660a4-9abd-4130-88ba-0991829f5559](https://user-images.githubusercontent.com/14966713/37017332-535c508a-20de-11e8-9713-368a4c7a3e3d.png)

**Comment by jackthmp** [comment]
Can you elaborate on what the issue is here?

**Comment by natashaarmbrust** [comment]
Oh yes, so I am subscribed to the series in the first screenshot (as shown by the second screenshot) but sometimes the button becomes unhighlighted. Im not sure if this is how we are updating the Cache (i.e. isSubscribed is off for one backend call).

My theory is that "isSubscribed" is not being returned for one call. When we parse a series from a json we use `json["isSubscribed"].boolValue` .. this defaults to false if `json["isSubscribed"]` does not exist. Since we are updating the cache then the series is not considered unsubscribed and the view update accordingly.

**Comment by jackthmp** [comment]
Note that the time update changes to "less than an hour ago" too, happens when you refresh feed

**Comment by natashaarmbrust** [comment]
explored, found a weird backend bug: [#208](https://github.com/cuappdev/podcast-backend/issues/208)
