### ISSUE TITLE
update "remove from saved for later" for when the episode is already saved

### ISSUE THREAD

**Issue by mindylou** [cuappdev/podcast-ios#284]
- unsure about the exact wording but make the option to unbookmark/remove from saved
- make this option in player too

![img_23b80c9c17c8-1](https://user-images.githubusercontent.com/20246620/37044452-7f19de92-2131-11e8-8973-31cf1cdfc0a0.jpeg)

**Comment by natashaarmbrust** [comment]
Oh shoot is it not here?

**Comment by mindylou** [comment]
no, like i saved/bookmarked the above episode and the options are to "save for later" again

**Comment by natashaarmbrust** [comment]
hmm that's weird .. i can't reproduce the issue

**Comment by natashaarmbrust** [comment]
<img width="310" alt="screen shot 2018-03-06 at 2 40 42 pm" src="https://user-images.githubusercontent.com/14966713/37054285-6bdc70b8-214c-11e8-8c7c-5a1545a7404c.png">

**Comment by mindylou** [comment]
oh wait I think I didn't update to master ... oops
