### ISSUE TITLE
Subscribe count at 0 when subscribed

### ISSUE THREAD

**Issue by jackthmp** [cuappdev/podcast-ios#285]
![simulator screen shot - iphone x - 2018-03-06 at 12 36 08](https://user-images.githubusercontent.com/34046832/37048170-131c6e62-213b-11e8-9dd9-14b714c82f2b.png)
![simulator screen shot - iphone x - 2018-03-06 at 12 36 13](https://user-images.githubusercontent.com/34046832/37048171-132a5ef0-213b-11e8-8ab9-1df1f21ac541.png)

Listed as 0 subscribers, even when I unsubscribe and resubscribe? Other series are fine:
![simulator screen shot - iphone x - 2018-03-06 at 12 36 26](https://user-images.githubusercontent.com/34046832/37048222-33b79c6e-213b-11e8-8da3-6f403465a237.png)

UPDATE: now showing -3 subscribers?
![image](https://user-images.githubusercontent.com/34046832/37048272-5d1d73f8-213b-11e8-8584-80afe58ca9a4.png)

**Comment by mindylou** [comment]
LOL I think this is a backend issue, I think there were some issues with wiping the DB so double check with them
