### ISSUE TITLE
Play Queue

### ISSUE THREAD

**Issue by say25** [cuappdev/podcast-ios#286]
Something I LOVE about the built in iOS podcast player is the ability to queue additional episodes to listen to later. When I go on a long car ride or get close to the end of an episode, I queue a couple of Podcasts up in a row.

**Comment by natashaarmbrust** [comment]
totally agree this would be an awesome feature .. we are working on immediate bug fixes as issues for rn so i am going to close and reopen later

**Comment by say25** [comment]
Reopen?
