### ISSUE TITLE
Add ability to cancel podcast downloads

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#306]
if you cancel a podcast download while it’s downloading it’ll still show downloaded but won’t show up in your downloaded stuff under the profile

Anyway we can show "downloading" podcasts in Downloads? Some users were confused at the progress (i.e. if it was finished etc) of the download when downloading from player

**Comment by doctor3w** [comment]
Cancelling downloads isn't a feature we have? I'm not sure how they cancelled it, if they click download again it just restarts the download.

**Comment by doctor3w** [comment]
Changed this to adding a cancel feature.
