### ISSUE TITLE
Discover Series Offset bug 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#319]
We are getting the same series twice (i checked and ids are the same for both entries of Love + Radio)

<img width="284" alt="screen shot 2018-03-08 at 11 41 19 pm" src="https://user-images.githubusercontent.com/14966713/37190900-916f2dae-232a-11e8-8958-ffe16e3fc837.png">

**Comment by mindylou** [comment]
closing this because it's a backend bug (non deterministic sorting algorithm)
