### ISSUE TITLE
General Data Persistence Issues

### ISSUE THREAD

**Issue by say25** [cuappdev/podcast-ios#339]
Feed doesnt know that I followed/unfollowed someone after clicking into their detail page.
Play progress doesnt update at the bottom of the screen

**Comment by say25** [comment]
![update](https://user-images.githubusercontent.com/7467062/37428837-7c9ce73e-279b-11e8-8a30-80e306835c5a.png)

**Comment by doctor3w** [comment]
LOL we don't persist data. Something we're working on.
