### ISSUE TITLE
Can’t pause player

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#346]
Apparently, you can't pause the player when using headphones!

**Comment by mindylou** [comment]
wait what? I've been using it with headphones and it's working for me

**Comment by natashaarmbrust** [comment]
Oh weird @eileendai said this was a bug! let me ask her to ask whoever reported it to elaborate!

**Comment by natashaarmbrust** [comment]
This is an issue when using the regular Apple earbuds. If this isn't an issue you are experiencing (/ you don't have Apple earbuds) I can reassign the bug.
