### ISSUE TITLE
"Shared with you" not displaying who shared with you properly

### ISSUE THREAD

**Issue by mindylou** [cuappdev/podcast-ios#351]
![img_1313](https://user-images.githubusercontent.com/20246620/37567157-30822d5e-2a99-11e8-97b3-e9a5708f69da.PNG)
![img_1314](https://user-images.githubusercontent.com/20246620/37567155-278504b0-2a99-11e8-8b7b-c5497e4a3195.PNG)
![img_1315](https://user-images.githubusercontent.com/20246620/37567168-75e01064-2a99-11e8-9b37-114d5d687168.PNG)

Jack shared the Intelligence Squared episode with me, but it says Jack shared another episode with me and that my other account shared the Intelligence Squared episode??

**Comment by natashaarmbrust** [comment]
confused .. can you explain at scrum!

**Comment by mindylou** [comment]
Closing because it's a backend bug

**Comment by natashaarmbrust** [comment]
Can you transfer this issue to backend github?? reference them to this note
