### ISSUE TITLE
Feed navigation bar disappearing 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#355]
I've come across this issue a number of times. Sometimes the navigation bar (transparency) will disappear in Feed. 

![img_1143](https://user-images.githubusercontent.com/14966713/37696290-ebc42496-2cab-11e8-9092-ad7581bf6798.PNG)

**Comment by mindylou** [comment]
I can't seem to replicate it, is there anything specific that you navigate to that causes it?

**Comment by natashaarmbrust** [comment]
it's happened a couple times on my phone as I am playing around .. I'm sure it will show up again so I"ll try to be conscious of it. For now, see if there is an obvious reason (as in check viewWillAppear, etc. in `Feed` / `ViewController`). If nothing stands out then leave it for now until someone (hopefully me soon) can provide more info on how to reproduce.

**Comment by natashaarmbrust** [comment]
This bug happens when you click on a person's external profile (then on another external profile from that profile) from Feed then press the home tab bar.

So a twice removed external profile then a home tab bar press (doesn't seem to be occurring if you just pop all the view controllers by pressing back)
