### ISSUE TITLE
Mini Player on iPhone X too low

### ISSUE THREAD

**Issue by jackthmp** [cuappdev/podcast-ios#394]
![image](https://user-images.githubusercontent.com/34046832/38456030-dd487cc8-3a4d-11e8-90f5-51032f1b8ee5.png)

Not sure if this is a safeAreaInsets thing or what

**Comment by jackthmp** [comment]
@mindylou can you fix this? this happened when you changed PlayerViewController for the new tab bar and used tabBarHeight as the y position of the collapsed player

**Comment by mindylou** [comment]
oh no!! yeah i can fix this
