### ISSUE TITLE
Facebook friends showing up in "shared with you"

### ISSUE THREAD

**Issue by mindylou** [cuappdev/podcast-ios#397]
this happens when you pull to refresh in "shared with you"
![img_1371](https://user-images.githubusercontent.com/20246620/38475333-713d4d5a-3b75-11e8-93c2-3d67a7c2e885.PNG)

**Comment by natashaarmbrust** [comment]
@mindylou we are removing this view controller when adding notifications right? So I shouldn't bother fixing since that will be in our next update

**Comment by mindylou** [comment]
true, i can close this
