### ISSUE TITLE
Model Changes Outline

### ISSUE THREAD

**Issue by doctor3w** [cuappdev/podcast-ios#400]
I'm making this an issue, but I'm going to do this in parts. I'm not exactly sure of the outline but I'm going to try and break it up into things I can PR slowly. 

Current plan: 

- Changes to DownloadManager (this is done really, I can push soon)
- Episode, Series, User Protocols for setting up different views with objects and handling actions that come out of these views (e.g. EpisodeViewProtocol and EpisodeActionDelegate). 
- Propose UserData storage model for eventual separation from our static models. This entails creating the model, making proper protocols to interact with it, but not actually implementing it into the controllers and views just yet. 
- Make static model changes, change views and delegates as needed, integrate realm. This is very far ahead but sadly may need to be done all together. 
- Make any changes that may have broken as a result of realm, cleanup, and what not.

**Comment by mindylou** [comment]
Looks good, couple questions: 
- is EpisodeViewProtocol/EpisodeActionDelegate in place of EpisodeManager? 
- the UserData model will be implemented with Realm, right?

You could also make this a checklist so you can cross stuff off as you continue working on the issue.

**Comment by doctor3w** [comment]
No EpisodeManager would be a separate thing that coincides with them. Those would just make all episode related views conform to the same protocol rather than creating their own.

**Comment by doctor3w** [comment]
And yes it should be but I'm still unsure what sort of objects we'll need to store that user data. It'll be backed by realm.

**Comment by natashaarmbrust** [comment]
This looks like a good breakdown Drew. We might want to create a PR for just the episode changes (protocol / manager) at first and then add in the User/Series protocols. It is something we should all thoroughly review and I don't want to make the PR overwhelming to review (and make!) by adding in User/Series at the same time.

**Comment by doctor3w** [comment]
Sure can do!
