### ISSUE TITLE
Create Custom Navigation Bar for playlist views

### ISSUE THREAD

**Issue by doctor3w** [cuappdev/podcast-ios#452]
**Designs**
Refer to Zeplin designs in our project.

**Comment by jackthmp** [comment]
![image](https://user-images.githubusercontent.com/34046832/48516749-21549400-e832-11e8-8990-9e1948d75727.png)
![image](https://user-images.githubusercontent.com/34046832/48516763-27e30b80-e832-11e8-81c7-38d93b90f22a.png)
