### ISSUE TITLE
Create deep links for podcasts for sharing

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-ios#85]
For MVP1, let's just reference the sharing to the podcast app and not a deeplink.. In the future, sharing an episode should reference that specific episode with a deeplink

**Comment by dennisfedorko** [comment]
what does this mean?

**Comment by doctor3w** [comment]
Deep links are fairly simple. We just need a URL format for our app. Otherwise I'm not sure how we'll share anything.
